// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY'),
    appId: '1:603114195895:web:9060a047506e3d1fcbb632',
    messagingSenderId: '603114195895',
    projectId: 'diary-app-vishal',
    authDomain: 'diary-app-vishal.firebaseapp.com',
    storageBucket: 'diary-app-vishal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY'),
    appId: '1:603114195895:android:ed043e80a7f22b08cbb632',
    messagingSenderId: '603114195895',
    projectId: 'diary-app-vishal',
    storageBucket: 'diary-app-vishal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY'),
    appId: '1:603114195895:ios:098877eb720cc64dcbb632',
    messagingSenderId: '603114195895',
    projectId: 'diary-app-vishal',
    storageBucket: 'diary-app-vishal.firebasestorage.app',
    iosBundleId: 'com.vishal.diaryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_MACOS_API_KEY'),
    appId: '1:603114195895:ios:224ffb8b92087b97cbb632',
    messagingSenderId: '603114195895',
    projectId: 'diary-app-vishal',
    storageBucket: 'diary-app-vishal.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WINDOWS_API_KEY'),
    appId: '1:603114195895:web:e1a4f488fbb8f75acbb632',
    messagingSenderId: '603114195895',
    projectId: 'diary-app-vishal',
    authDomain: 'diary-app-vishal.firebaseapp.com',
    storageBucket: 'diary-app-vishal.firebasestorage.app',
  );
}
